CREATE TABLE tb_destination(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    picture VARCHAR(2048) NOT NULL,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2),
    is_active TINYINT DEFAULT 1
);